# ha config
homeassistant:

################################################################################
## BASE SETUP
################################################################################

  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  #customize: !include customize.yaml
################################################################################
## PACKAGES
################################################################################

  packages: !include_dir_named packages

################################################################################
## FRONTEND
################################################################################

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:


################################################################################
## FUNCTIONALITY
################################################################################

updater: null
discovery: null
ios: null
python_script: null
system_log: null

################################################################################
## VOICE INTERFACE
################################################################################

conversation: null
tts:
  platform: google

################################################################################
## WEB INTERFACE
################################################################################

config: null
hassio: null
history: null
logbook: null
map: null
#shopping_list: null

################################################################################
## Z-WAVE
################################################################################

# zwave:
#   usb_path: /dev/ttyUSB0